name: boardforge_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^10.1.2
  dio: ^5.9.0
  flutter_secure_storage: ^4.2.1
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.1.0
  build_runner: ^2.5.4

flutter:
  uses-material-design: true
  assets:
    - development.env
    - production.env
    - assets/images/avatar.jpeg
